
# Makefile test

all:
	#g++ HalideRaw.cpp -g -I ~/packages/Halide/include/ -I ~/packages/Halide/tools -L ~/packages/Halide/bin -lHalide `libpng-config --cflags --ldflags` -lpthread -ldl -lraw -lm -o HalideRaw -std=c++11 
	g++ ImgPipe_Halide.cpp LoadCamModel.cpp -g -I ~/packages/Halide/include/ -I ~/packages/Halide/tools -L ~/packages/Halide/bin -lHalide `libpng-config --cflags --ldflags` -lpthread -ldl -lraw -lm -o ImgPipe -std=c++11
